# Generated by Django 3.0.2 on 2020-06-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finches',
            new_name='Finch',
        ),
    ]
